### ISSUE TITLE
Django 1.7 Errors in application

### ISSUE THREAD

**Issue by vinaychandra** [coleifer/django-relationships#40]
Using this app in django 1.7b4 raises the following error

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 427, in execute_from_command_line
utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 391, in execute
django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 21, in setup
apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 106, in populate
app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 190, in import_models
self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
__import__(name)
  File "build/bdist.linux-x86_64/egg/relationships/models.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/relationships/compat.py", line 7, in <module>
  File "/usr/local/lib/python2.7/dist-packages/django/contrib/auth/__init__.py", line 136, in get_user_model
return django_apps.get_model(settings.AUTH_USER_MODEL)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 187, in get_model
self.check_ready()
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 119, in check_ready
raise RuntimeError("App registry isn't ready yet.")
RuntimeError: App registry isn't ready yet.
```

**Comment by thisiscam** [comment]
It's kinkd of late, but I've prevented this error
https://github.com/thisiscam/django-relationships/commit/4dbc38d6981e67a8088e471b01ef188cb055bdef
But I still can't use the injected user.relationships.add
